/* Sınıfa Özel Bölge İkonları — kazanım temalı (MEB Sosyal Bilgiler) */
const REGION_TOPIC_ICONS_GRADED = {
  // ============================================================
  // 5. SINIF — Bölgemizi Tanıyalım (temel ürün, kültür, sembol)
  // ============================================================
  5: {
    marmara: [
      { emoji: "🌉", label: "Boğaz Köprüsü", city: "İstanbul", lat: 41.04, lng: 29.03,
        desc: "Asya ve Avrupa'yı birbirine bağlayan ünlü asma köprü. Marmara'nın simgesidir." },
      { emoji: "🕌", label: "Ayasofya", city: "İstanbul", lat: 41.01, lng: 28.98,
        desc: "Bin yılı aşkın tarihiyle İstanbul'un en önemli yapısı. Bizans ve Osmanlı izleri taşır." },
      { emoji: "🏰", label: "Topkapı Sarayı", city: "İstanbul", lat: 41.01, lng: 28.98,
        desc: "Osmanlı padişahlarının yaşadığı görkemli saray. Bugün önemli bir müzedir." },
      { emoji: "⚓", label: "Çanakkale Boğazı", city: "Çanakkale", lat: 40.15, lng: 26.41,
        desc: "Akdeniz'i Marmara'ya bağlayan dar deniz geçidi. Tarihi savaşlara sahne olmuştur." },
      { emoji: "🌷", label: "Edirne Lalesi", city: "Edirne", lat: 41.68, lng: 26.56,
        desc: "Osmanlı'nın eski başkenti Edirne, lale ve Selimiye Camii ile ünlüdür." },
      { emoji: "🛍️", label: "Kapalıçarşı", city: "İstanbul", lat: 41.01, lng: 28.97,
        desc: "Dünyanın en eski kapalı çarşılarından biri. Binlerce dükkânıyla ünlüdür." },
      { emoji: "🌊", label: "Marmara Denizi", city: "Marmara", lat: 40.65, lng: 28.20,
        desc: "Tamamı ülkemiz sınırları içinde olan tek denizimizdir. Bölgeye adını verir." },
      { emoji: "🍽️", label: "İskender Kebap", city: "Bursa", lat: 40.20, lng: 29.07,
        desc: "Bursa'nın dünyaca ünlü yöresel yemeği. Yoğurt ve tereyağı ile servis edilir." },
    ],
    karadeniz: [
      { emoji: "🍵", label: "Çay Bahçeleri", city: "Rize", lat: 41.02, lng: 40.52,
        desc: "Rize, Türkiye'nin çay deposudur. Yağışlı iklim çay tarımına çok uygundur." },
      { emoji: "🌰", label: "Fındık Bahçesi", city: "Giresun", lat: 40.91, lng: 38.39,
        desc: "Giresun ve çevresi dünya fındık üretiminin önemli bir kısmını sağlar." },
      { emoji: "🌧️", label: "Bol Yağış", city: "Rize", lat: 41.02, lng: 40.52,
        desc: "Karadeniz Bölgesi en çok yağış alan bölgemizdir. Yıl boyunca yağış görülür." },
      { emoji: "🎻", label: "Kemençe", city: "Trabzon", lat: 41.00, lng: 39.72,
        desc: "Karadeniz'in vazgeçilmez halk müziği aletidir. Horon oynanırken çalınır." },
      { emoji: "💃", label: "Horon", city: "Trabzon", lat: 41.00, lng: 39.72,
        desc: "Karadeniz'in coşkulu halk oyunudur. Ellerden tutulup hızlı ritimle oynanır." },
      { emoji: "🌳", label: "Yayla", city: "Rize", lat: 40.66, lng: 41.10,
        desc: "Yüksek yerlerdeki çayırlık alanlardır. Yaz aylarında hayvanlar otlatılır." },
      { emoji: "🐟", label: "Hamsi", city: "Trabzon", lat: 41.00, lng: 39.72,
        desc: "Karadeniz'in en sevilen balığıdır. Pek çok yöresel yemeği yapılır." },
      { emoji: "🍞", label: "Mısır Ekmeği", city: "Trabzon", lat: 41.00, lng: 39.72,
        desc: "Karadeniz'de mısır çok yetişir. Mısır unundan yapılan ekmek yörenin temel yiyeceğidir." },
    ],
    ege: [
      { emoji: "🫒", label: "Zeytin Bahçesi", city: "Aydın", lat: 37.85, lng: 27.85,
        desc: "Ege Bölgesi Türkiye'nin zeytin deposudur. Aydın ve İzmir öne çıkar." },
      { emoji: "🍇", label: "Üzüm Bağı", city: "Manisa", lat: 38.62, lng: 27.42,
        desc: "Manisa'nın çekirdeksiz üzümü dünyaca ünlüdür. Kuru üzüm de buradan ihraç edilir." },
      { emoji: "🏛️", label: "Efes Antik Kenti", city: "İzmir", lat: 37.94, lng: 27.34,
        desc: "Selçuk'taki bu antik kent UNESCO Dünya Mirası'dır. Celsus Kütüphanesi ünlüdür." },
      { emoji: "🌊", label: "Ege Denizi", city: "Ege", lat: 38.50, lng: 26.50,
        desc: "Berrak suları ve girintili kıyıları ile bölgenin simgesidir. Birçok ada barındırır." },
      { emoji: "🏖️", label: "Çeşme Plajı", city: "İzmir", lat: 38.32, lng: 26.30,
        desc: "Ege'nin ünlü tatil merkezidir. Temiz denizi ve rüzgârıyla ünlüdür." },
      { emoji: "🍑", label: "İncir", city: "Aydın", lat: 37.85, lng: 27.85,
        desc: "Aydın inciri dünyaca tanınır. Hem taze hem kuru olarak tüketilir." },
      { emoji: "🚜", label: "Pamuk Tarlası", city: "Denizli", lat: 37.78, lng: 29.09,
        desc: "Ege ovalarında pamuk üretilir. Tekstil sanayisinin ham maddesidir." },
      { emoji: "🎶", label: "Zeybek Oyunu", city: "Aydın", lat: 37.85, lng: 27.85,
        desc: "Ege'nin yiğitlik temalı halk oyunudur. Ağır ve görkemli figürler içerir." },
    ],
    icanadolu: [
      { emoji: "🏛️", label: "Anıtkabir", city: "Ankara", lat: 39.92, lng: 32.83,
        desc: "Atatürk'ün anıt mezarıdır. Başkentimiz Ankara'da bulunur." },
      { emoji: "🌾", label: "Buğday Tarlası", city: "Konya", lat: 37.87, lng: 32.49,
        desc: "Konya Ovası ülkemizin tahıl ambarıdır. Ekmeğimiz buradan gelir." },
      { emoji: "🏔️", label: "Kapadokya Peri Bacaları", city: "Nevşehir", lat: 38.65, lng: 34.83,
        desc: "Volkanik kayaların aşınmasıyla oluşan eşsiz manzaradır. UNESCO Dünya Mirası'dır." },
      { emoji: "🧂", label: "Tuz Gölü", city: "Aksaray", lat: 38.78, lng: 33.38,
        desc: "Türkiye'nin tuz ihtiyacının büyük kısmını karşılayan ikinci büyük gölümüzdür." },
      { emoji: "🎈", label: "Sıcak Hava Balonu", city: "Nevşehir", lat: 38.64, lng: 34.83,
        desc: "Kapadokya'nın simgesi haline gelmiştir. Gün doğumunda gökyüzünü süsler." },
      { emoji: "🐑", label: "Koyun Sürüsü", city: "Konya", lat: 37.87, lng: 32.49,
        desc: "Geniş bozkırlarda küçükbaş hayvancılık yaygındır. Yün ve süt sağlar." },
      { emoji: "❄️", label: "Karasal İklim", city: "Ankara", lat: 39.92, lng: 32.83,
        desc: "Yazları sıcak ve kurak, kışları soğuk geçer. Bozkır bitki örtüsü hâkimdir." },
      { emoji: "🏛️", label: "Mevlana Türbesi", city: "Konya", lat: 37.87, lng: 32.50,
        desc: "Mevlana Celaleddin Rumi'nin türbesidir. Sema gösterileri ile ünlüdür." },
    ],
    akdeniz: [
      { emoji: "🍊", label: "Portakal Bahçesi", city: "Antalya", lat: 36.90, lng: 30.71,
        desc: "Akdeniz iklimi turunçgillerin yetişmesi için idealdir. Antalya ve Mersin öne çıkar." },
      { emoji: "🍋", label: "Limon Bahçesi", city: "Mersin", lat: 36.81, lng: 34.64,
        desc: "Mersin limon üretiminde Türkiye birincisidir. İhracatın önemli bir kısmı buradan yapılır." },
      { emoji: "🌴", label: "Muz Serası", city: "Antalya", lat: 36.55, lng: 31.99,
        desc: "Anamur ve Alanya çevresinde muz yetiştirilir. Sıcak iklim sayesinde ürün vermektedir." },
      { emoji: "🏖️", label: "Konyaaltı Plajı", city: "Antalya", lat: 36.86, lng: 30.65,
        desc: "Antalya'nın ünlü plajıdır. Mavi bayraklı temiz denizi ile turistlerin gözdesidir." },
      { emoji: "🏛️", label: "Aspendos", city: "Antalya", lat: 36.94, lng: 31.17,
        desc: "Roma döneminden kalma muhteşem antik tiyatrodur. Hâlâ konser verilir." },
      { emoji: "☀️", label: "Akdeniz Güneşi", city: "Antalya", lat: 36.90, lng: 30.71,
        desc: "Yılın büyük kısmı güneşli geçer. Bu yüzden turizmde Türkiye birincisidir." },
      { emoji: "🥒", label: "Sera Tarımı", city: "Antalya", lat: 36.96, lng: 30.79,
        desc: "Kumluca ve Demre'de seralarda sebze yetiştirilir. Kışın bile üretim yapılır." },
      { emoji: "🍯", label: "Çam Balı", city: "Muğla", lat: 37.21, lng: 28.36,
        desc: "Muğla yöresinin ünlü çam balı dünyaca bilinir. Bölgenin önemli ürünüdür." },
    ],
    doguanadolu: [
      { emoji: "🏔️", label: "Ağrı Dağı", city: "Ağrı", lat: 39.70, lng: 44.30,
        desc: "Türkiye'nin en yüksek dağıdır (5137 m). Sönmüş bir volkandır." },
      { emoji: "💧", label: "Van Gölü", city: "Van", lat: 38.65, lng: 43.00,
        desc: "Türkiye'nin en büyük gölüdür. Tuzlu ve sodalı suyu vardır." },
      { emoji: "🐈", label: "Van Kedisi", city: "Van", lat: 38.50, lng: 43.40,
        desc: "İki gözü ayrı renkte olan ünlü kedimizdir. Suyu ve yüzmeyi sever." },
      { emoji: "❄️", label: "Karlı İklim", city: "Erzurum", lat: 39.90, lng: 41.27,
        desc: "Doğu Anadolu kışları çok soğuk geçer. Karın yerde kaldığı süre uzundur." },
      { emoji: "🐄", label: "Büyükbaş Hayvancılık", city: "Erzurum", lat: 39.90, lng: 41.27,
        desc: "Geniş otlaklar büyükbaş hayvancılığa elverişlidir. Et ve süt üretilir." },
      { emoji: "🧀", label: "Kars Kaşar Peyniri", city: "Kars", lat: 40.60, lng: 43.10,
        desc: "Kars'ın yüksek otlaklarından elde edilen kaşar peyniri ünlüdür." },
      { emoji: "🏰", label: "İshak Paşa Sarayı", city: "Ağrı", lat: 39.52, lng: 44.27,
        desc: "Doğubayazıt'taki tarihi saraydır. Anadolu'nun son büyük taş yapılarındandır." },
      { emoji: "🍯", label: "Erzurum Cağ Kebabı", city: "Erzurum", lat: 39.90, lng: 41.27,
        desc: "Erzurum'un ünlü yöresel yemeğidir. Yatay şişte odun ateşinde pişirilir." },
    ],
    guneydogu: [
      { emoji: "🌾", label: "Pamuk Tarlası", city: "Şanlıurfa", lat: 37.16, lng: 38.79,
        desc: "GAP sayesinde Harran ovasında pamuk bolca yetişir. Tekstilin ham maddesidir." },
      { emoji: "🥜", label: "Antep Fıstığı", city: "Gaziantep", lat: 37.07, lng: 37.38,
        desc: "Gaziantep'in dünyaca ünlü ürünüdür. Baklavaya tat ve renk verir." },
      { emoji: "🍮", label: "Antep Baklavası", city: "Gaziantep", lat: 37.07, lng: 37.38,
        desc: "Coğrafi işaretli ünlü tatlımızdır. Kat kat yufka ve fıstık ile yapılır." },
      { emoji: "🏛️", label: "Göbeklitepe", city: "Şanlıurfa", lat: 37.22, lng: 38.92,
        desc: "Dünyanın bilinen en eski tapınağıdır (12.000 yaşında). UNESCO Dünya Mirası'dır." },
      { emoji: "🐟", label: "Balıklıgöl", city: "Şanlıurfa", lat: 37.15, lng: 38.79,
        desc: "Hz. İbrahim'in atıldığına inanılan kutsal göldür. Sazanları yenmez." },
      { emoji: "🪨", label: "Mardin Taş Evleri", city: "Mardin", lat: 37.31, lng: 40.74,
        desc: "Sarımsı taşlardan yapılmış geleneksel Mardin evleri. Açık hava müzesi gibidir." },
      { emoji: "☀️", label: "Sıcak ve Kurak İklim", city: "Şanlıurfa", lat: 37.16, lng: 38.79,
        desc: "Yazları çok sıcak ve kuraktır. Kışları ılıman geçer." },
      { emoji: "🌶️", label: "Urfa Biberi", city: "Şanlıurfa", lat: 37.16, lng: 38.79,
        desc: "Şanlıurfa'nın ünlü acı biberidir. Yöresel yemeklerin vazgeçilmezidir." },
    ],
  },

  // ============================================================
  // 6. SINIF — Yeryüzü Şekilleri ve Sular (fiziki coğrafya)
  // ============================================================
  6: {
    marmara: [
      { emoji: "⛷️", label: "Uludağ", city: "Bursa", lat: 40.10, lng: 29.22,
        desc: "Marmara Bölgesi'nin en yüksek dağıdır (2543 m). Kayak merkezi olarak ünlüdür." },
      { emoji: "💧", label: "Sapanca Gölü", city: "Sakarya", lat: 40.71, lng: 30.27,
        desc: "Tatlı sulu tektonik gölümüzdür. Çevre illerin içme suyunu sağlar." },
      { emoji: "🌊", label: "Sakarya Nehri", city: "Sakarya", lat: 40.95, lng: 30.40,
        desc: "İç Anadolu'dan doğup Karadeniz'e dökülen önemli akarsuyumuzdur." },
      { emoji: "💧", label: "İznik Gölü", city: "Bursa", lat: 40.45, lng: 29.55,
        desc: "Tektonik kökenli tatlı su gölüdür. Kıyısında tarihi İznik şehri yer alır." },
      { emoji: "⚠️", label: "Kuzey Anadolu Fayı", city: "Kocaeli", lat: 40.74, lng: 29.97,
        desc: "Türkiye'nin en aktif fay hattıdır. Marmara'dan geçer ve depremlere yol açar." },
      { emoji: "⛏️", label: "Mermer Yatakları", city: "Balıkesir", lat: 40.42, lng: 27.72,
        desc: "Marmara Adası ve çevresi mermer üretiminde önemlidir. İhraç ürünümüzdür." },
      { emoji: "🌳", label: "Trakya Ovası", city: "Tekirdağ", lat: 41.10, lng: 27.15,
        desc: "Ergene Ovası tahıl üretiminde önemlidir. Düz arazileri tarıma elverişlidir." },
      { emoji: "🏞️", label: "Kocaeli Yarımadası", city: "Kocaeli", lat: 40.85, lng: 29.85,
        desc: "Plato karakterinde alçak yer şekilleri içerir. Sanayi tesislerine ev sahipliği yapar." },
    ],
    karadeniz: [
      { emoji: "🏔️", label: "Kuzey Anadolu Dağları", city: "Trabzon", lat: 40.85, lng: 39.50,
        desc: "Karadeniz kıyısı boyunca uzanan dağ silsilesidir. İklimi büyük ölçüde etkiler." },
      { emoji: "🌊", label: "Kızılırmak", city: "Samsun", lat: 41.71, lng: 35.95,
        desc: "Türkiye'nin en uzun nehridir (1355 km). Karadeniz'e dökülür." },
      { emoji: "🌊", label: "Yeşilırmak", city: "Samsun", lat: 41.36, lng: 36.30,
        desc: "Tokat ve Amasya'dan geçerek Samsun'da Karadeniz'e dökülür. Bafra Ovası'nı oluşturur." },
      { emoji: "🌊", label: "Çoruh Nehri", city: "Artvin", lat: 41.18, lng: 41.82,
        desc: "Türkiye'nin en hızlı akan nehridir. Rafting için idealdir." },
      { emoji: "💧", label: "Uzungöl", city: "Trabzon", lat: 40.62, lng: 40.30,
        desc: "Heyelan set gölüdür. Yeşillikler içindeki manzarasıyla turist çeker." },
      { emoji: "⛏️", label: "Zonguldak Taş Kömürü", city: "Zonguldak", lat: 41.45, lng: 31.79,
        desc: "Türkiye'nin tek taş kömürü havzasıdır. Sanayinin önemli ham maddesidir." },
      { emoji: "⛏️", label: "Murgul Bakırı", city: "Artvin", lat: 41.19, lng: 41.55,
        desc: "Artvin Murgul, Türkiye'nin önemli bakır madeni yataklarındandır." },
      { emoji: "🏞️", label: "Bafra Ovası", city: "Samsun", lat: 41.55, lng: 35.90,
        desc: "Kızılırmak'ın oluşturduğu delta ovasıdır. Tarıma çok elverişlidir." },
    ],
    ege: [
      { emoji: "🏔️", label: "Bozdağlar", city: "İzmir", lat: 38.32, lng: 28.07,
        desc: "Ege Bölgesi'nde doğu-batı yönlü uzanan dağ silsilesidir. Aralarında ovalar bulunur." },
      { emoji: "🌊", label: "Büyük Menderes", city: "Aydın", lat: 37.74, lng: 27.59,
        desc: "Adı 'menderes' kelimesinin kaynağıdır. Ege Denizi'ne dökülür." },
      { emoji: "🌊", label: "Gediz Nehri", city: "İzmir", lat: 38.61, lng: 26.85,
        desc: "Ege Bölgesi'nin önemli nehridir. İzmir Körfezi'ne dökülür ve delta oluşturur." },
      { emoji: "💧", label: "Bafa Gölü", city: "Muğla", lat: 37.50, lng: 27.42,
        desc: "Eskiden bir körfez iken kapanmasıyla oluşan göldür. Doğal güzelliği ile bilinir." },
      { emoji: "🏞️", label: "Pamukkale Travertenleri", city: "Denizli", lat: 37.92, lng: 29.12,
        desc: "Karstik kökenli, kireçten oluşan beyaz travertenlerdir. UNESCO Dünya Mirası'dır." },
      { emoji: "🏞️", label: "Menderes Ovası", city: "Aydın", lat: 37.85, lng: 27.85,
        desc: "Akarsu birikintilerinden oluşmuş verimli ova. Pamuk ve incir tarımı yapılır." },
      { emoji: "⛏️", label: "Soma Linyiti", city: "Manisa", lat: 39.18, lng: 27.61,
        desc: "Manisa Soma'da büyük linyit kömürü yatakları vardır. Termik santrali besler." },
      { emoji: "⛏️", label: "Bor Madeni", city: "Kütahya", lat: 39.42, lng: 29.99,
        desc: "Emet'te dünyanın en büyük bor rezervleri vardır. Türkiye dünya birincisidir." },
    ],
    icanadolu: [
      { emoji: "🏔️", label: "Erciyes Dağı", city: "Kayseri", lat: 38.53, lng: 35.45,
        desc: "İç Anadolu'nun en yüksek dağıdır (3917 m). Sönmüş bir volkandır, kayak merkezidir." },
      { emoji: "🏔️", label: "Hasan Dağı", city: "Aksaray", lat: 38.13, lng: 34.17,
        desc: "Sönmüş volkanik dağdır (3268 m). Çatalhöyük duvar resimlerinde de yer alır." },
      { emoji: "🌊", label: "Kızılırmak Kaynağı", city: "Sivas", lat: 39.85, lng: 38.32,
        desc: "Türkiye'nin en uzun nehri Sivas'tan doğar. İç Anadolu'yu kıvrılarak geçer." },
      { emoji: "💧", label: "Tuz Gölü", city: "Aksaray", lat: 38.78, lng: 33.38,
        desc: "Türkiye'nin ikinci büyük gölüdür. Kapalı havzadadır, çok tuzludur." },
      { emoji: "💧", label: "Beyşehir Gölü", city: "Konya", lat: 37.78, lng: 31.50,
        desc: "Türkiye'nin üçüncü büyük gölüdür. Tatlı sulu, tarıma su sağlar." },
      { emoji: "🏞️", label: "Konya Ovası", city: "Konya", lat: 37.87, lng: 32.49,
        desc: "Türkiye'nin tahıl ambarıdır. Geniş düzlüklerde buğday ekilir." },
      { emoji: "🏔️", label: "Peri Bacaları", city: "Nevşehir", lat: 38.65, lng: 34.83,
        desc: "Volkanik tüflerin aşınmasıyla oluşan jeolojik şekillerdir. Kapadokya'ya özgüdür." },
      { emoji: "⛏️", label: "Sivas Demir Yatakları", city: "Sivas", lat: 39.75, lng: 37.02,
        desc: "Divriği'de zengin demir madeni vardır. Karabük ve Ereğli'de işlenir." },
    ],
    akdeniz: [
      { emoji: "🏔️", label: "Toros Dağları", city: "Antalya", lat: 36.78, lng: 31.40,
        desc: "Akdeniz kıyısı boyunca uzanan yüksek dağ silsilesidir. İklimi belirler." },
      { emoji: "🌊", label: "Seyhan Nehri", city: "Adana", lat: 36.99, lng: 35.32,
        desc: "Toroslardan doğup Akdeniz'e dökülür. Çukurova'yı sular." },
      { emoji: "🌊", label: "Ceyhan Nehri", city: "Adana", lat: 37.02, lng: 35.81,
        desc: "Çukurova'yı sulayan ikinci büyük nehirdir. Akdeniz'e dökülür." },
      { emoji: "💧", label: "Eğirdir Gölü", city: "Isparta", lat: 38.05, lng: 30.87,
        desc: "Türkiye'nin dördüncü büyük gölüdür. Tatlı sulu, balıkçılık yapılır." },
      { emoji: "💧", label: "Burdur Gölü", city: "Burdur", lat: 37.72, lng: 30.18,
        desc: "Tektonik kökenli, hafif tuzlu göldür. Su seviyesi giderek azalmaktadır." },
      { emoji: "🏞️", label: "Çukurova", city: "Adana", lat: 36.99, lng: 35.32,
        desc: "Türkiye'nin en büyük delta ovasıdır. Pamuk başta olmak üzere tarıma elverişlidir." },
      { emoji: "🏞️", label: "Karstik Mağaralar", city: "Antalya", lat: 37.10, lng: 30.93,
        desc: "Toroslar'ın kireç taşı yapısı binlerce mağara oluşturmuştur. Damlataş ünlüdür." },
      { emoji: "⛏️", label: "Krom Madeni", city: "Antalya", lat: 37.21, lng: 31.16,
        desc: "Akdeniz Bölgesi'nde Toros eteklerinde krom madeni çıkarılır. İhracat ürünüdür." },
    ],
    doguanadolu: [
      { emoji: "🏔️", label: "Ağrı Dağı", city: "Ağrı", lat: 39.70, lng: 44.30,
        desc: "Türkiye'nin en yüksek noktasıdır (5137 m). Sönmüş volkandır, zirvesi karlıdır." },
      { emoji: "🏔️", label: "Süphan Dağı", city: "Bitlis", lat: 38.92, lng: 42.82,
        desc: "Türkiye'nin ikinci yüksek volkanik dağıdır (4058 m). Van Gölü'nün kuzeyindedir." },
      { emoji: "🌊", label: "Fırat Nehri", city: "Erzurum", lat: 39.78, lng: 41.05,
        desc: "Erzurum yakınlarından doğar. Türkiye'den geçen en uzun akarsuyumuzdur." },
      { emoji: "🌊", label: "Murat Nehri", city: "Muş", lat: 38.74, lng: 41.50,
        desc: "Fırat'ın en büyük koludur. Doğu Anadolu'yu boylu boyunca geçer." },
      { emoji: "💧", label: "Van Gölü", city: "Van", lat: 38.65, lng: 43.00,
        desc: "Türkiye'nin en büyük gölüdür (3713 km²). Volkanik set gölüdür, sodalıdır." },
      { emoji: "🏞️", label: "Erzurum-Kars Platosu", city: "Erzurum", lat: 39.90, lng: 41.27,
        desc: "Türkiye'nin en yüksek ve en geniş platosudur. Hayvancılığa elverişlidir." },
      { emoji: "🏞️", label: "Iğdır Ovası", city: "Iğdır", lat: 39.92, lng: 44.05,
        desc: "Doğu Anadolu'nun en alçak yeridir. Mikroklima sayesinde meyvecilik yapılır." },
      { emoji: "⛏️", label: "Divriği Demir", city: "Sivas", lat: 39.37, lng: 38.12,
        desc: "Türkiye'nin en zengin demir yataklarındandır. Doğu Anadolu sınırına yakındır." },
    ],
    guneydogu: [
      { emoji: "🏔️", label: "Karacadağ", city: "Diyarbakır", lat: 37.67, lng: 39.83,
        desc: "Sönmüş bir volkanik dağdır. Etekleri tarıma elverişlidir, buğdayın anavatanıdır." },
      { emoji: "🌊", label: "Fırat Nehri", city: "Şanlıurfa", lat: 37.49, lng: 38.30,
        desc: "Bölgeyi sulayan en önemli akarsudur. Atatürk Barajı üzerine kurulmuştur." },
      { emoji: "🌊", label: "Dicle Nehri", city: "Diyarbakır", lat: 37.91, lng: 40.22,
        desc: "Diyarbakır'dan geçerek Suriye'ye akar. Mezopotamya'nın iki büyük nehrinden biridir." },
      { emoji: "💧", label: "Atatürk Barajı", city: "Şanlıurfa", lat: 37.48, lng: 38.32,
        desc: "Türkiye'nin en büyük barajıdır. GAP'ın kalbidir, elektrik üretir ve sulama yapar." },
      { emoji: "🏞️", label: "Harran Ovası", city: "Şanlıurfa", lat: 36.86, lng: 39.03,
        desc: "GAP sayesinde sulanan verimli ovadır. Pamuk ve mısır yetiştirilir." },
      { emoji: "🏞️", label: "Diyarbakır Bazalt Platosu", city: "Diyarbakır", lat: 37.91, lng: 40.22,
        desc: "Karacadağ'dan akan lavlarla oluşmuş plato. Siyah bazalt taşlar yaygındır." },
      { emoji: "⛏️", label: "Batman Petrolü", city: "Batman", lat: 37.89, lng: 41.13,
        desc: "Türkiye'nin en önemli petrol kuyularındandır. Rafineri burada bulunur." },
      { emoji: "⛏️", label: "Şırnak Asfaltiti", city: "Şırnak", lat: 37.52, lng: 42.46,
        desc: "Asfaltit, kömüre benzeyen yakıt taşıdır. Şırnak'ın önemli yer altı kaynağıdır." },
    ],
  },

  // ============================================================
  // 7. SINIF — Tarihte Yolculuk + Ekonomi/Yaşam (UNESCO, sanayi)
  // ============================================================
  7: {
    marmara: [
      { emoji: "🏭", label: "Bursa Otomotiv Sanayi", city: "Bursa", lat: 40.20, lng: 29.07,
        desc: "Türkiye'nin otomotiv başkentidir. TOFAŞ ve Renault burada üretim yapar." },
      { emoji: "🛍️", label: "İstanbul Tekstil Merkezi", city: "İstanbul", lat: 41.04, lng: 28.97,
        desc: "Laleli ve Merter, hazır giyim ihracatının kalbi sayılır. İstanbul önemli sanayi merkezidir." },
      { emoji: "🛬", label: "İstanbul Havalimanı", city: "İstanbul", lat: 41.27, lng: 28.74,
        desc: "Dünyanın en büyük havalimanlarından biridir. 2018'de açılmıştır." },
      { emoji: "🚢", label: "Ambarlı Limanı", city: "İstanbul", lat: 40.98, lng: 28.69,
        desc: "Türkiye'nin en yoğun konteyner limanlarındandır. İhracat ve ithalatın merkezidir." },
      { emoji: "🚇", label: "Marmaray", city: "İstanbul", lat: 41.00, lng: 29.00,
        desc: "Asya ile Avrupa'yı boğaz altından bağlayan demir yoludur. 2013'te açılmıştır." },
      { emoji: "🏛️", label: "Selimiye Camii (UNESCO)", city: "Edirne", lat: 41.68, lng: 26.56,
        desc: "Mimar Sinan'ın 'ustalık eserim' dediği yapısıdır. UNESCO Dünya Mirası listesindedir." },
      { emoji: "🌷", label: "Tarihi Yarımada (UNESCO)", city: "İstanbul", lat: 41.01, lng: 28.97,
        desc: "Sultanahmet, Ayasofya, Topkapı çevresi UNESCO listesindedir. Bizans-Osmanlı mirasını taşır." },
      { emoji: "🛣️", label: "Kuzey Marmara Otoyolu", city: "Kocaeli", lat: 40.85, lng: 29.85,
        desc: "Yavuz Sultan Selim Köprüsü ile birlikte yapılmıştır. Trafiği rahatlatır." },
    ],
    karadeniz: [
      { emoji: "🏭", label: "Karabük Demir Çelik", city: "Karabük", lat: 41.20, lng: 32.63,
        desc: "Türkiye'nin ilk demir çelik fabrikasıdır (1937). Sanayileşmenin sembolüdür." },
      { emoji: "🏭", label: "Ereğli Demir Çelik", city: "Zonguldak", lat: 41.28, lng: 31.41,
        desc: "ERDEMİR Türkiye'nin en büyük çelik üreticisidir. Sanayinin temel ham maddesini sağlar." },
      { emoji: "🚢", label: "Samsun Limanı", city: "Samsun", lat: 41.29, lng: 36.34,
        desc: "Karadeniz'in en büyük limanlarındandır. İhracatta önemli rol oynar." },
      { emoji: "🛬", label: "Trabzon Havalimanı", city: "Trabzon", lat: 41.00, lng: 39.79,
        desc: "Karadeniz'in en yoğun havalimanıdır. Yurtdışı uçuşlarıyla bağlantı sağlar." },
      { emoji: "🏛️", label: "Sümela Manastırı", city: "Trabzon", lat: 40.69, lng: 39.66,
        desc: "Kayalara oyulmuş tarihi Hristiyan manastırıdır. Karadeniz'in turist çeken anıtıdır." },
      { emoji: "🏛️", label: "Safranbolu Evleri (UNESCO)", city: "Karabük", lat: 41.25, lng: 32.69,
        desc: "Geleneksel Osmanlı evleri ile UNESCO Dünya Mirası'dır. Açık hava müzesi gibidir." },
      { emoji: "⛷️", label: "Kartalkaya Kayak Merkezi", city: "Bolu", lat: 40.62, lng: 31.78,
        desc: "Bolu'daki popüler kayak merkezidir. Kış turizminde önemli yer tutar." },
      { emoji: "🌳", label: "Ayder Yaylası Turizmi", city: "Rize", lat: 40.95, lng: 41.10,
        desc: "Ünlü yayla turizm merkezidir. Kaplıcaları ve doğasıyla bilinir." },
    ],
    ege: [
      { emoji: "🏛️", label: "Efes Antik Kenti (UNESCO)", city: "İzmir", lat: 37.94, lng: 27.34,
        desc: "Antik dünyanın en görkemli şehirlerindendir. UNESCO Dünya Mirası listesindedir." },
      { emoji: "🏛️", label: "Bergama (UNESCO)", city: "İzmir", lat: 39.13, lng: 27.18,
        desc: "Helenistik dönemin önemli şehridir. Tıp tanrısı Asklepios'un tapınağı buradadır." },
      { emoji: "🏛️", label: "Pamukkale-Hierapolis (UNESCO)", city: "Denizli", lat: 37.92, lng: 29.12,
        desc: "Beyaz travertenleri ve antik şehri ile UNESCO Dünya Mirası'dır." },
      { emoji: "🚢", label: "Alsancak Limanı", city: "İzmir", lat: 38.45, lng: 27.15,
        desc: "Ege'nin en büyük limanıdır. İhracatın önemli kapısıdır." },
      { emoji: "🛬", label: "Adnan Menderes Havalimanı", city: "İzmir", lat: 38.29, lng: 27.16,
        desc: "Ege'nin merkez havalimanıdır. Yoğun yurtdışı trafiği vardır." },
      { emoji: "🏭", label: "Denizli Tekstil", city: "Denizli", lat: 37.78, lng: 29.09,
        desc: "Ev tekstili (havlu, bornoz) üretiminde dünya markası olmuştur. İhracat şampiyonudur." },
      { emoji: "🏖️", label: "Bodrum Turizmi", city: "Muğla", lat: 37.04, lng: 27.43,
        desc: "Mavi yolculuğun başlangıç noktasıdır. Halikarnas Mausoleionu burada bulunmuştur." },
      { emoji: "🏛️", label: "Truva (UNESCO)", city: "Çanakkale", lat: 39.96, lng: 26.24,
        desc: "Homeros'un İlyada destanına konu olan antik şehirdir. UNESCO Dünya Mirası'dır." },
    ],
    icanadolu: [
      { emoji: "🏛️", label: "Hattuşa (UNESCO)", city: "Çorum", lat: 40.02, lng: 34.62,
        desc: "Hitit İmparatorluğu'nun başkentidir. UNESCO Dünya Mirası listesindedir." },
      { emoji: "🏛️", label: "Çatalhöyük (UNESCO)", city: "Konya", lat: 37.67, lng: 32.83,
        desc: "Dünyanın bilinen en eski yerleşim yerlerindendir (9000 yıl). UNESCO listesindedir." },
      { emoji: "🏛️", label: "Anıtkabir", city: "Ankara", lat: 39.92, lng: 32.83,
        desc: "Atatürk'ün anıt mezarıdır. Cumhuriyet'in en önemli sembolüdür." },
      { emoji: "🏭", label: "Eskişehir Lokomotif Fabrikası", city: "Eskişehir", lat: 39.78, lng: 30.52,
        desc: "TÜLOMSAŞ Türkiye'nin tek lokomotif üreticisidir. Sanayinin önemli kalesidir." },
      { emoji: "🏭", label: "Kayseri Mobilya Sanayisi", city: "Kayseri", lat: 38.73, lng: 35.48,
        desc: "Türkiye mobilya üretiminin önemli merkezidir. Boydak, İstikbal markaları buradan çıkar." },
      { emoji: "🛬", label: "Esenboğa Havalimanı", city: "Ankara", lat: 40.13, lng: 32.99,
        desc: "Başkentin uluslararası havalimanıdır. Yoğun trafik kapasitesine sahiptir." },
      { emoji: "⛷️", label: "Erciyes Kayak Merkezi", city: "Kayseri", lat: 38.53, lng: 35.45,
        desc: "Türkiye'nin en modern kayak merkezlerindendir. Erciyes Dağı eteklerindedir." },
      { emoji: "🎈", label: "Kapadokya Turizmi (UNESCO)", city: "Nevşehir", lat: 38.65, lng: 34.83,
        desc: "Peri bacaları ve yer altı şehirleri ile UNESCO Dünya Mirası'dır. Balon turlarıyla ünlüdür." },
    ],
    akdeniz: [
      { emoji: "🏭", label: "Adana Tekstil Sanayi", city: "Adana", lat: 37.00, lng: 35.32,
        desc: "Çukurova pamuğunu işleyen büyük tekstil merkezidir. Türkiye sanayisinin önemli halkasıdır." },
      { emoji: "🏛️", label: "Aspendos Tiyatrosu", city: "Antalya", lat: 36.94, lng: 31.17,
        desc: "Roma'dan kalma muhteşem antik tiyatrodur. Hâlâ konser verilmektedir." },
      { emoji: "🏛️", label: "Likya Yolu", city: "Antalya", lat: 36.20, lng: 30.30,
        desc: "Antik Likya kentlerini birbirine bağlayan tarihi yürüyüş yoludur. 540 km uzunluğundadır." },
      { emoji: "🚢", label: "Mersin Limanı", city: "Mersin", lat: 36.79, lng: 34.62,
        desc: "Türkiye'nin en büyük konteyner limanlarındandır. Doğu Akdeniz ticaretinin merkezidir." },
      { emoji: "🛬", label: "Antalya Havalimanı", city: "Antalya", lat: 36.90, lng: 30.80,
        desc: "Türkiye'nin en yoğun turist havalimanıdır. Yıl boyu uçuş trafiği yoğundur." },
      { emoji: "🏖️", label: "Side Antik Kent ve Plajı", city: "Antalya", lat: 36.77, lng: 31.39,
        desc: "Antik kent ile plajın iç içe olduğu turistik merkezdir. Apollon Tapınağı ünlüdür." },
      { emoji: "⛷️", label: "Saklıkent Kayak Merkezi", city: "Antalya", lat: 36.80, lng: 30.32,
        desc: "Sabah denize, öğleden sonra kayağa imkan veren ilginç bölgedir. Toroslar'ın eteklerindedir." },
      { emoji: "🛣️", label: "TAG Otoyolu", city: "Adana", lat: 36.99, lng: 35.32,
        desc: "Tarsus-Adana-Gaziantep otoyolu, Doğu-Batı bağlantısının kalbidir. İhracat trafiğine hizmet eder." },
    ],
    doguanadolu: [
      { emoji: "🏛️", label: "Nemrut Dağı (UNESCO)", city: "Adıyaman", lat: 37.98, lng: 38.74,
        desc: "Kommagene Krallığı'nın dev heykelleriyle UNESCO Dünya Mirası'dır. Gün doğumu ünlüdür." },
      { emoji: "🏛️", label: "İshak Paşa Sarayı", city: "Ağrı", lat: 39.52, lng: 44.27,
        desc: "Doğubayazıt'taki 18. yy yapısı görkemli bir saraydır. Anadolu'nun son taş eseridir." },
      { emoji: "🏛️", label: "Akdamar Kilisesi", city: "Van", lat: 38.34, lng: 43.04,
        desc: "Van Gölü'ndeki adada 10. yy'dan kalan kilisedir. Taş kabartmalarıyla ünlüdür." },
      { emoji: "🏛️", label: "Erzurum Çifte Minareli Medrese", city: "Erzurum", lat: 39.91, lng: 41.27,
        desc: "Selçuklu mimarisinin başyapıtıdır. Tarihi taş işçiliği görülmeye değerdir." },
      { emoji: "⛷️", label: "Palandöken Kayak Merkezi", city: "Erzurum", lat: 39.86, lng: 41.27,
        desc: "Türkiye'nin en uzun pistlerine sahip kayak merkezidir. Olimpiyat seviyesindedir." },
      { emoji: "🛬", label: "Erzurum Havalimanı", city: "Erzurum", lat: 39.96, lng: 41.17,
        desc: "Doğu Anadolu'nun ana havalimanıdır. Kış turizmine hizmet verir." },
      { emoji: "🚂", label: "Doğu Ekspresi", city: "Kars", lat: 40.60, lng: 43.10,
        desc: "Ankara-Kars arasında işleyen tarihi tren hattıdır. Karlı manzaralarıyla ünlüdür." },
      { emoji: "🏭", label: "Elazığ Krom İşletmesi", city: "Elazığ", lat: 38.68, lng: 39.22,
        desc: "Etibakır işletmesi krom ve bakır üretir. Bölgenin önemli sanayisidir." },
    ],
    guneydogu: [
      { emoji: "🏛️", label: "Göbeklitepe (UNESCO)", city: "Şanlıurfa", lat: 37.22, lng: 38.92,
        desc: "12.000 yıl öncesine ait dünyanın en eski tapınağıdır. UNESCO Dünya Mirası'dır." },
      { emoji: "🏛️", label: "Diyarbakır Surları (UNESCO)", city: "Diyarbakır", lat: 37.91, lng: 40.22,
        desc: "Çin Seddi'nden sonra dünyanın en uzun sur sistemidir. UNESCO Dünya Mirası'dır." },
      { emoji: "🏛️", label: "Mardin Tarihi Kenti", city: "Mardin", lat: 37.31, lng: 40.74,
        desc: "Sarı taş evleri ve dini yapılarıyla açık hava müzesi gibidir. UNESCO geçici listesindedir." },
      { emoji: "🏛️", label: "Zeugma Mozaikleri", city: "Gaziantep", lat: 37.06, lng: 37.38,
        desc: "Gaziantep Müzesi'nde sergilenen Roma mozaikleridir. 'Çingene Kızı' dünyaca ünlüdür." },
      { emoji: "🏭", label: "Gaziantep Sanayi", city: "Gaziantep", lat: 37.07, lng: 37.38,
        desc: "Halı, makine halısı ve gıda sanayisinde Türkiye'nin önde gelen şehridir." },
      { emoji: "🛬", label: "Şanlıurfa GAP Havalimanı", city: "Şanlıurfa", lat: 37.45, lng: 38.90,
        desc: "GAP bölgesine hizmet veren havalimanıdır. Bölgesel turizmi destekler." },
      { emoji: "🚢", label: "Habur Sınır Kapısı", city: "Şırnak", lat: 37.24, lng: 42.45,
        desc: "Türkiye'nin Irak'a açılan en yoğun kara sınır kapısıdır. Ticarette kritik öneme sahiptir." },
      { emoji: "🛣️", label: "Nizip-Birecik Yolu", city: "Gaziantep", lat: 37.03, lng: 37.97,
        desc: "Güneydoğu'yu birbirine bağlayan ana yoldur. Tarihi ipek yolu güzergâhındadır." },
    ],
  },

  // ============================================================
  // 8. SINIF — Doğal Afet, Sürdürülebilirlik, Yenilenebilir Enerji
  // ============================================================
  8: {
    marmara: [
      { emoji: "⚠️", label: "1999 Gölcük Depremi", city: "Kocaeli", lat: 40.74, lng: 29.97,
        desc: "17 Ağustos 1999'da yaşanan büyük depremdir. Marmara'da yıkıma yol açmıştır." },
      { emoji: "⚠️", label: "Kuzey Anadolu Fayı", city: "Sakarya", lat: 40.78, lng: 30.40,
        desc: "Türkiye'nin en aktif fay hattıdır. Marmara depremi beklenen bölgede yer alır." },
      { emoji: "🌫️", label: "Müsilaj Kirliliği", city: "Marmara", lat: 40.65, lng: 28.20,
        desc: "Marmara Denizi'nde görülen 'deniz salyası'dır. Aşırı kirlilik ve ısınma sebep olur." },
      { emoji: "💨", label: "Bandırma Rüzgar Santrali", city: "Balıkesir", lat: 40.35, lng: 27.97,
        desc: "Bandırma çevresinde büyük rüzgar tarlaları bulunur. Yenilenebilir enerji üretir." },
      { emoji: "♻️", label: "İSTAÇ Geri Dönüşüm", city: "İstanbul", lat: 41.05, lng: 28.95,
        desc: "İstanbul'un atık yönetimini ve geri dönüşümünü yapan kuruluştur. Çevre dostudur." },
      { emoji: "☀️", label: "Çanakkale Güneş Santrali", city: "Çanakkale", lat: 40.15, lng: 26.41,
        desc: "Bölgede kurulan büyük güneş enerjisi santralleri yenilenebilir elektrik üretir." },
      { emoji: "🌳", label: "Belgrad Ormanı", city: "İstanbul", lat: 41.18, lng: 28.97,
        desc: "İstanbul'un akciğeridir. Doğal hayatı korur ve hava kirliliğini azaltır." },
      { emoji: "🚜", label: "Trakya Sürdürülebilir Tarım", city: "Edirne", lat: 41.50, lng: 26.80,
        desc: "Trakya ovasında çevre dostu tarım uygulamaları yaygınlaşmaktadır. Toprağı korur." },
    ],
    karadeniz: [
      { emoji: "⚠️", label: "Heyelan Riski", city: "Rize", lat: 41.02, lng: 40.52,
        desc: "Karadeniz'in dik yamaçları ve bol yağışı heyelana sebep olur. Sık karşılaşılan afettir." },
      { emoji: "⚠️", label: "Sel Felaketleri", city: "Giresun", lat: 40.91, lng: 38.39,
        desc: "Aşırı yağışlar sel ve taşkınlara yol açar. 2020 Giresun seli büyük zarar vermiştir." },
      { emoji: "💨", label: "Sinop Rüzgar Santrali", city: "Sinop", lat: 42.02, lng: 35.15,
        desc: "Karadeniz kıyılarındaki rüzgar enerjisi yatırımıdır. Temiz elektrik üretir." },
      { emoji: "💧", label: "HES (Hidroelektrik)", city: "Artvin", lat: 41.18, lng: 41.82,
        desc: "Çoruh Nehri üzerindeki hidroelektrik santralleri elektrik üretir. Yenilenebilir kaynaktır." },
      { emoji: "🌳", label: "Küre Dağları Milli Parkı", city: "Kastamonu", lat: 41.85, lng: 33.65,
        desc: "Avrupa'nın 100 sıcak orman noktasından biridir. Biyoçeşitliliği korur." },
      { emoji: "🌳", label: "Yeniköy Yangın Olayları", city: "Bolu", lat: 40.74, lng: 31.61,
        desc: "Yaz kuraklığında orman yangınları riski artar. Müdahale ekipleri hazırdır." },
      { emoji: "♻️", label: "Trabzon Atık Yönetimi", city: "Trabzon", lat: 41.00, lng: 39.72,
        desc: "Şehirde modern atık tesisi geri dönüşüm yapar. Çevreyi korumaya katkı sağlar." },
      { emoji: "🐟", label: "Hamsi Sürdürülebilir Avcılığı", city: "Samsun", lat: 41.29, lng: 36.34,
        desc: "Aşırı avlanma hamsi stoğunu tehdit eder. Av yasağı dönemleri uygulanır." },
    ],
    ege: [
      { emoji: "⚠️", label: "İzmir Depremi (2020)", city: "İzmir", lat: 38.39, lng: 26.79,
        desc: "30 Ekim 2020'de Seferihisar açıklarında yaşanan depremdir. Bayraklı'da yıkım olmuştur." },
      { emoji: "🔥", label: "Manavgat Yangını (2021)", city: "Antalya", lat: 36.79, lng: 31.44,
        desc: "Ege ve Akdeniz'de büyük orman yangınları yaşanmıştır. İklim değişikliği etkisidir." },
      { emoji: "💨", label: "Çeşme Rüzgar Santrali", city: "İzmir", lat: 38.32, lng: 26.30,
        desc: "Ege kıyılarındaki rüzgar Türkiye'nin en büyük rüzgar santrallerini besler." },
      { emoji: "♨️", label: "Aydın Jeotermal", city: "Aydın", lat: 37.85, lng: 28.05,
        desc: "Aydın ve Denizli Türkiye'nin jeotermal başkentidir. Sera ve ısınmada kullanılır." },
      { emoji: "☀️", label: "Karapınar Güneş", city: "Konya", lat: 37.71, lng: 33.55,
        desc: "Konya yakınında olsa da Ege bağlantılı; iç bölgelerden büyük güneş tarlasıdır." },
      { emoji: "🐢", label: "Caretta Caretta", city: "Muğla", lat: 36.81, lng: 28.62,
        desc: "İztuzu Plajı (Dalyan) deniz kaplumbağalarının yumurtlama alanıdır. Koruma altındadır." },
      { emoji: "🌊", label: "Ege Deniz Kirliliği", city: "İzmir", lat: 38.45, lng: 27.10,
        desc: "İzmir Körfezi atık ve liman trafiğinden etkilenir. Temizleme çalışmaları sürer." },
      { emoji: "🌳", label: "Dilek Yarımadası Milli Parkı", city: "Aydın", lat: 37.69, lng: 27.15,
        desc: "Doğal Akdeniz makilerini ve nadir hayvanları koruyan milli parktır." },
    ],
    icanadolu: [
      { emoji: "⚠️", label: "Tuz Gölü Kuruması", city: "Aksaray", lat: 38.78, lng: 33.38,
        desc: "İklim değişikliği ve aşırı su kullanımı Tuz Gölü'nü tehdit ediyor. Kuş ölümleri yaşanmıştır." },
      { emoji: "🔥", label: "Bozkır Yangını Riski", city: "Konya", lat: 37.87, lng: 32.49,
        desc: "Yaz kuraklığı bozkırda yangın riskini artırır. Tarım arazileri tehdit altındadır." },
      { emoji: "💨", label: "Sivas Rüzgar Santrali", city: "Sivas", lat: 39.75, lng: 37.02,
        desc: "İç Anadolu yüksek platolarında rüzgar enerjisi yatırımları artmaktadır. Temiz enerjidir." },
      { emoji: "☀️", label: "Karapınar Güneş Tarlası", city: "Konya", lat: 37.71, lng: 33.55,
        desc: "Türkiye'nin en büyük güneş enerjisi santrallerindendir. 1300 MW kapasitelidir." },
      { emoji: "♨️", label: "Kırşehir Jeotermal", city: "Kırşehir", lat: 39.15, lng: 34.16,
        desc: "Termal kaynaklarla seralarda üretim ve ısıtma yapılır. Yenilenebilir enerjidir." },
      { emoji: "💧", label: "Kuraklık ve Kuyular", city: "Konya", lat: 37.87, lng: 32.49,
        desc: "Konya Ovası'nda yer altı suyu hızla azalıyor, obruklar oluşuyor. Sürdürülebilir tarım gerekli." },
      { emoji: "🕳️", label: "Konya Obrukları", city: "Konya", lat: 37.40, lng: 32.66,
        desc: "Yer altı suyunun azalması ile büyük çukurlar oluşuyor. Karapınar çevresinde sıktır." },
      { emoji: "🌳", label: "Salda Gölü Koruma", city: "Aksaray", lat: 38.43, lng: 34.32,
        desc: "İç Anadolu'nun nadir göllerinden Acıgöl ve çevresi koruma altındadır. Flamingoları barındırır." },
    ],
    akdeniz: [
      { emoji: "🔥", label: "Manavgat Orman Yangını", city: "Antalya", lat: 36.79, lng: 31.44,
        desc: "2021 yazındaki büyük yangın binlerce hektar ormanı yok etti. İklim krizinin habercisidir." },
      { emoji: "🔥", label: "Marmaris Yangını", city: "Muğla", lat: 36.85, lng: 28.27,
        desc: "Akdeniz kıyılarında sıcak ve kuru hava yangınları artırır. Koruma çalışmaları yoğunlaşmıştır." },
      { emoji: "⚠️", label: "Doğu Anadolu Fayı", city: "Hatay", lat: 36.20, lng: 36.16,
        desc: "6 Şubat 2023 depremlerinin merkez üssü çevresidir. DAF üzerinde yaşanan büyük afettir." },
      { emoji: "💨", label: "Belen Rüzgar Santrali", city: "Hatay", lat: 36.49, lng: 36.20,
        desc: "Hatay Belen'de büyük rüzgar enerjisi tesisleri vardır. Bölgenin elektrik ihtiyacını karşılar." },
      { emoji: "☀️", label: "Antalya Güneş Enerjisi", city: "Antalya", lat: 36.90, lng: 30.71,
        desc: "Yıl boyu güneşli olan Antalya'da güneş paneli yatırımları büyür. Çatı GES'leri yaygındır." },
      { emoji: "🐢", label: "Caretta Caretta Koruma", city: "Antalya", lat: 36.27, lng: 30.50,
        desc: "Belek ve Patara plajları kaplumbağa yumurta alanlarıdır. Geceleri ışık yasağı vardır." },
      { emoji: "🌊", label: "Akdeniz Foku", city: "Antalya", lat: 36.21, lng: 29.78,
        desc: "Nesli tükenmek üzere olan Akdeniz fokları Foça ve Kaş'ta görülür. Koruma altındadır." },
      { emoji: "💧", label: "Su Kıtlığı", city: "Adana", lat: 36.99, lng: 35.32,
        desc: "Akdeniz bölgesi kuraklık baskısı altında. Damla sulama sürdürülebilirlik için yaygınlaşıyor." },
    ],
    doguanadolu: [
      { emoji: "⚠️", label: "Van Depremi (2011)", city: "Van", lat: 38.73, lng: 43.45,
        desc: "23 Ekim 2011'de yaşanan büyük depremdir. Erciş'te ağır hasara yol açmıştır." },
      { emoji: "⚠️", label: "Doğu Anadolu Fayı", city: "Elazığ", lat: 38.68, lng: 39.22,
        desc: "DAF, Türkiye'nin diğer büyük fay hattıdır. 2020 Elazığ depreminin nedeni olmuştur." },
      { emoji: "🌨️", label: "Çığ Tehlikesi", city: "Bitlis", lat: 38.40, lng: 42.10,
        desc: "Yüksek dağlık alanlarda kar birikmesiyle çığlar oluşur. Yolları kapatabilir." },
      { emoji: "💨", label: "Kars Rüzgar Santrali", city: "Kars", lat: 40.60, lng: 43.10,
        desc: "Yüksek plato rüzgar enerjisine elverişlidir. Doğu'da yenilenebilir enerji yatırımı yapılır." },
      { emoji: "💧", label: "Keban Barajı", city: "Elazığ", lat: 38.81, lng: 38.75,
        desc: "Türkiye'nin en büyük barajlarındandır. Hidroelektrik üretir, Fırat üzerindedir." },
      { emoji: "💧", label: "Karakaya Barajı", city: "Diyarbakır", lat: 38.23, lng: 39.16,
        desc: "Fırat üzerindeki büyük HES'tir. Yenilenebilir elektrik üretir." },
      { emoji: "🌳", label: "Munzur Milli Parkı", city: "Tunceli", lat: 39.20, lng: 39.43,
        desc: "Endemik bitkileriyle koruma altındaki milli parktır. Munzur Vadisi eşsizdir." },
      { emoji: "❄️", label: "Aşırı Soğuk", city: "Erzurum", lat: 39.90, lng: 41.27,
        desc: "Doğu Anadolu kışları çok soğuktur. -30°C'ye inebilir, donma riski yüksektir." },
    ],
    guneydogu: [
      { emoji: "⚠️", label: "Kahramanmaraş Depremi (2023)", city: "Kahramanmaraş", lat: 37.58, lng: 36.93,
        desc: "6 Şubat 2023'te yaşanan asrın felaketidir. 11 ili etkileyen büyük afettir." },
      { emoji: "⚠️", label: "DAF (Doğu Anadolu Fayı)", city: "Adıyaman", lat: 37.76, lng: 38.28,
        desc: "Güneydoğu'yu boylu boyunca geçen aktif fay hattıdır. 2023 depremlerinin nedenidir." },
      { emoji: "🔥", label: "Sıcak Dalgası", city: "Şanlıurfa", lat: 37.16, lng: 38.79,
        desc: "Yazları 45°C'yi aşan sıcaklık görülür. İklim değişikliği etkisi şiddetlenmektedir." },
      { emoji: "💧", label: "Atatürk Barajı (HES)", city: "Şanlıurfa", lat: 37.48, lng: 38.32,
        desc: "Türkiye'nin en büyük HES'idir. GAP'ın temelidir, tarım ve elektrik için kritiktir." },
      { emoji: "☀️", label: "Şanlıurfa Güneş Enerjisi", city: "Şanlıurfa", lat: 37.16, lng: 38.79,
        desc: "Türkiye'nin en çok güneş alan ilidir. Büyük GES yatırımları yapılır." },
      { emoji: "💨", label: "Gaziantep Rüzgar", city: "Gaziantep", lat: 37.07, lng: 37.38,
        desc: "Bölgede rüzgar enerjisi tesisleri kurulmaktadır. Yenilenebilir enerji çeşitlenir." },
      { emoji: "🌳", label: "Hasankeyf-Ilısu Etkisi", city: "Batman", lat: 37.71, lng: 41.41,
        desc: "Ilısu Barajı tarihi Hasankeyf'i sular altında bıraktı. Çevresel ve kültürel tartışma yaratmıştır." },
      { emoji: "💧", label: "Kuraklık ve GAP", city: "Diyarbakır", lat: 37.91, lng: 40.22,
        desc: "Bölgede kuraklık riski sürdürülebilir tarımı zorunlu kılar. GAP suyu verimli kullanılmalıdır." },
    ],
  },
};

Object.assign(window, { REGION_TOPIC_ICONS_GRADED });
